In [ ]:
# Paralelización (Solver: Lineales o no lineales).
# Petsc

In [ ]:
!pip install petsc4py #

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 428.1/428.1 kB 5.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... canceled
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_r

In [ ]:
# Anaconda (Jupyter-Notebook)
# Utilizar las herramientas de petsc (Localmente)
# MUMPS (Jupyter-Notebook)
# PETSC

# 5 noviembre (solvers con librerias en paralelo)

# Normas para una buena escritura de Python:
# https://peps.python.org/pep-0257/

# * Pandas
# * Scipy sparse (matrices dispersas)
# * Clases de funciones (Programación orientada a objeto)
# * decoradores...
# * binders (crear un archivo: CMake (c++)
# * binder con Fortran

# * Escribir un archivo archivo.sh (python)

# * Git (Github)
# * Gitlab
# * https://bitbucket.org/product/



# Solver directos optimizados por libreria scipy (matrices dispersas)

In [ ]:
import numpy as np
import scipy.linalg as spla

# Definimos una matriz

A = np.array([[3,1,6],[2,1,3],[1,1,1]])
b = np.array([9,7,3])


In [ ]:
#factorización lu

lu_piv  = spla.lu_factor(A)

x = spla.lu_solve(lu_piv,b)
print(x)

print(lu_piv)

[ 8. -3. -2.]
(array([[ 3.        ,  1.        ,  6.        ],
       [ 0.33333333,  0.66666667, -1.        ],
       [ 0.66666667,  0.5       , -0.5       ]]), array([0, 2, 2], dtype=int32))


In [ ]:
import numpy as np
from scipy.linalg import cho_factor, cho_solve
A = np.array([[9, 3, 1, 5], [3, 7, 5, 1], [1, 5, 9, 2], [5, 1, 2, 6]])
c, low = cho_factor(A) # realiza la descomposicion de cholesky de A y devuelve una matriz triangular inferior (y un indicador pasa saber si la parte superior o inferior que se ha almacenado)


x = cho_solve((c, low), [1, 1, 1, 1]) #cho_solve utiliza la descomposicion de Cholesky para resolver el sitema A x= b
x

array([-0.01749271,  0.11953353,  0.01166181,  0.1574344 ])

In [ ]:
# material complementario: Cuenta el numero de operaciones que se necesitan
# Cramer
# lu
# cholesky

In [ ]:
# Métodos iterativos:
# Método de Jacobi

# Implementación del método de Jacobi en Scipy

Para este metodo se necesita que Diagonal no sea cero, si no hay que permutar.

$$ A x = b$$

$$ PA x = Pb $$

(Métodos precondicionador)

In [ ]:
import numpy as np
from scipy.linalg import norm

In [ ]:
# Definir la matriz A y el vector b
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]])

b = np.array([15, 10, 10, 10])

In [ ]:
# Condiciones iniciales
x = np.zeros_like(b)  # Vector inicial (x0)

# Ax_0 = b;  x_0 = 0
# A(x_1) = b

tolerancia = 1e-10   # Tolerancia para la convergencia
max_iteraciones = 1000  # Máximo número de iteraciones


In [ ]:
# Implementación del método de Jacobi usando scipy/numpy
def jacobi_scipy(A, b, x, tolerancia, max_iteraciones):
    D = np.diag(np.diag(A))     # Extrae la diagonal de A
    L_plus_U = A - D            # Matriz L + U

    for k in range(max_iteraciones):
        x_nuevo = (b - np.dot(L_plus_U, x)) / np.diag(A)  # Fórmula de Jacobi
        # Comprobar la convergencia
        if norm(x_nuevo - x, ord=np.inf) < tolerancia:
            print(f"Convergencia alcanzada en {k+1} iteraciones.")
            return x_nuevo
        x = x_nuevo

    print("Número máximo de iteraciones alcanzado.")
    return x

# Método del gradiente conjugado:
# A debe ser simétrica y definida positiva.

Minimizar este problema
$$ \phi(x)= \frac{1}{2} x^tA x -b^t x $$

In [ ]:
import numpy as np
from scipy.sparse.linalg import cg

# Definir la matriz A (simétrica y definida positiva) y el vector b
A = np.array([[4, 1], [1, 3]])
b = np.array([1, 2])

x0 = np.zeros_like(b)

# Definir la matriz A (simétrica y definida positiva) y el vector b
A = np.array([[4, 1], [1, 3]])
b = np.array([1, 2])

x = cg(A, b, x0)
x


(array([0.09090909, 0.63636364]), 0)

In [ ]:
help(cg)

Help on function cg in module scipy.sparse.linalg._isolve.iterative:

cg(A, b, x0=None, *, tol=<object object at 0x797d38f1a230>, maxiter=None, M=None, callback=None, atol=0.0, rtol=1e-05)
    Use Conjugate Gradient iteration to solve ``Ax = b``.
    
    Parameters
    ----------
    A : {sparse matrix, ndarray, LinearOperator}
        The real or complex N-by-N matrix of the linear system.
        ``A`` must represent a hermitian, positive definite matrix.
        Alternatively, ``A`` can be a linear operator which can
        produce ``Ax`` using, e.g.,
        ``scipy.sparse.linalg.LinearOperator``.
    b : ndarray
        Right hand side of the linear system. Has shape (N,) or (N,1).
    x0 : ndarray
        Starting guess for the solution.
    rtol, atol : float, optional
        Parameters for the convergence test. For convergence,
        ``norm(b - A @ x) <= max(rtol*norm(b), atol)`` should be satisfied.
        The default is ``atol=0.`` and ``rtol=1e-5``.
    maxiter : integ

Como resolver este problema
$$
\begin{pmatrix}
A & B \\
B^t & 0
\end{pmatrix}
\begin{pmatrix}
x_1 \\
x_2
\end{pmatrix}
=
\begin{pmatrix}
b_1 \\
b_2
\end{pmatrix}
$$

$Ax = b$

Resolver con gmres

$$ Ax_1 + Bx_2 = b_1$$
$$B^t x_1 = b_2$$

$$x_1 + A^{-1}B x_2 = A^{-1}b_1$$
$$B^tx_1 = b_2 $$

$$ B^tx_1 + B^t A^{-1}B x_2 = A^{-1}b_1 $$


$$ B^t A^{-1} B x_2 = A^{-1} b_1  - b_2$$

In [ ]:
import numpy as np
from scipy.sparse.linalg import gmres

# Definir la matriz A
A = np.array([[4, 1], [1, 3]])
b = np.array([1, 2])

x0 = np.zeros_like(b)

# Definir la matriz A (simétrica y definida positiva) y el vector b
A = np.array([[4, 1], [1, 3]]) #simetrica y definida positiva
b = np.array([1, 2])

x = gmres(A, b, x0)
x


(array([0.09090909, 0.63636364]), 0)

In [ ]:
# Solvers (No lineales)

In [ ]:
#A no es cuadrada

# min \| Ax-b\|